services:
  mysql:
    image: mysql:latest
    container_name: task-manager-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Chanu&369
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql